In [37]:
#arithmetic 1D array
import numpy as np 
arr = np.arange(101,117)
arr

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116])

In [38]:
arr+1

array([102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
       115, 116, 117])

In [39]:
1/arr

array([0.00990099, 0.00980392, 0.00970874, 0.00961538, 0.00952381,
       0.00943396, 0.00934579, 0.00925926, 0.00917431, 0.00909091,
       0.00900901, 0.00892857, 0.00884956, 0.00877193, 0.00869565,
       0.00862069])

In [40]:
arr*arr

array([10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881,
       12100, 12321, 12544, 12769, 12996, 13225, 13456])

In [41]:
#arithmetic 2d array
arr_2d = arr.reshape(4,4)
arr_2d

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112],
       [113, 114, 115, 116]])

In [42]:
arr_2d**2

array([[10201, 10404, 10609, 10816],
       [11025, 11236, 11449, 11664],
       [11881, 12100, 12321, 12544],
       [12769, 12996, 13225, 13456]], dtype=int32)

In [44]:
arr_1d = np.array([1,2,3,4])
arr_2d*arr_1d

array([[101, 204, 309, 416],
       [105, 212, 321, 432],
       [109, 220, 333, 448],
       [113, 228, 345, 464]])

In [45]:
arr_2d/arr_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [46]:
#squareroot
np.sqrt(arr)

array([10.04987562, 10.09950494, 10.14889157, 10.19803903, 10.24695077,
       10.29563014, 10.34408043, 10.39230485, 10.44030651, 10.48808848,
       10.53565375, 10.58300524, 10.63014581, 10.67707825, 10.72380529,
       10.77032961])

In [47]:
#exponential (e^)
np.exp(arr)

array([7.30705998e+43, 1.98626484e+44, 5.39922761e+44, 1.46766223e+45,
       3.98951957e+45, 1.08446386e+46, 2.94787839e+46, 8.01316426e+46,
       2.17820388e+47, 5.92097203e+47, 1.60948707e+48, 4.37503945e+48,
       1.18925902e+49, 3.23274119e+49, 8.78750164e+49, 2.38869060e+50])

In [48]:
#trigonometric sine
np.sin(arr_2d)

array([[ 0.45202579,  0.99482679,  0.62298863, -0.3216224 ],
       [-0.97053528, -0.7271425 ,  0.18478174,  0.92681851],
       [ 0.81674261, -0.04424268, -0.86455145, -0.8899956 ],
       [-0.09718191,  0.78498039,  0.94543533,  0.23666139]])

In [49]:
#natural logarithm, the inverse of exponential
np.log(arr_2d)

array([[4.61512052, 4.62497281, 4.63472899, 4.6443909 ],
       [4.65396035, 4.66343909, 4.67282883, 4.68213123],
       [4.69134788, 4.70048037, 4.7095302 , 4.71849887],
       [4.72738782, 4.73619845, 4.74493213, 4.75359019]])

In [59]:
#other function, insert, delete, append
np.insert(arr,5,10)

array([101, 102, 103, 104, 105,  10, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116])

In [51]:
np.delete(arr,7)

array([101, 102, 103, 104, 105, 106, 107, 109, 110, 111, 112, 113, 114,
       115, 116])

In [52]:
np.append(arr,11)

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116,  11])

In [53]:
#concatenate[
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a, b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])

In [55]:
np.concatenate((a,b), axis = None)

array([1, 2, 3, 4, 5, 6])

In [56]:
#where
np.where(arr>5,1,arr)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [57]:
np.where(arr>5,1,0)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [58]:
np.where(arr_2d <=5,0,arr_2d)

array([[101, 102, 103, 104],
       [105, 106, 107, 108],
       [109, 110, 111, 112],
       [113, 114, 115, 116]])